### ISSUE TITLE
AttributeError: module 'scipy.ndimage' has no attribute 'imread'

### ISSUE THREAD

**Issue by e-dub** [PolymerGuy/muDIC#12]
I am getting this error with scipy version 1.3.0

Any ideas what I may be doing wrong? 

Thanks!

**Comment by PolymerGuy** [comment]
Hi!
Thanks for the question!

They have removed imread from ndimage after scipy 1.2.1.
As a quick fix, I froze Scipy to version 1.2.1 in the requirements file.

If this is unpractical, we could move to another package such as imageio for imread?

Best regards
Sindre

**Comment by e-dub** [comment]
I just tried opencv2 (cv2) for the imread, but it did not like the flatten command.  I changed to $TERM.flatten(), but then there was another issue with array size.

**Comment by PolymerGuy** [comment]
I can give it a go. Did you clone the repo or install it via PIP?

**Comment by e-dub** [comment]
I cloned muDIC, installed opencv by apt install python3-openc

**Comment by PolymerGuy** [comment]
I have now changed from ndimage.imread to imageio.imread.

Try to pull the changes  (or clone it once more) and it should work

**Comment by e-dub** [comment]
We are good. Thanks!
