### ISSUE TITLE
No convergence with 10% strain

### ISSUE THREAD

**Issue by valentinpy** [PolymerGuy/muDIC#14]
I'm unable to make a convergence using to attached images. The second image is a 110% zoom of the first one.
Small zoom values (101..103%) work perfectly and strain measurement is quite accurate!

Is the displacement / strain  too big ?

![0V](https://user-images.githubusercontent.com/1656847/65436973-46873b00-de23-11e9-8ecf-397e3bf486ac.jpg)
![0V_enlarged_1 10](https://user-images.githubusercontent.com/1656847/65436972-46873b00-de23-11e9-96b9-0caa038ea940.jpg)

**Comment by PolymerGuy** [comment]
Hi! Lovely to see a novel application of the toolkit!

It's hard to tell exactly how you are doing the analysis, but I guess you are attempting to correlate two images? By that, I mean that you go straight from the reference to 110% magnification?
If this is the case, then yes, that could be a too big increase of deformation in one step. We normally gradually increase the deformation, say you gradually ramp up the deformation (100%,101%,102% etc) until we reach the desired values. If you cannot do this, then you might try using a single linear element (deg_e=1,deg_n=1), as it tends to be the easiest to make converge.

Really looking forward to hearing how this goes! "and I am quite curious about what is pictured on the image)

**Comment by valentinpy** [comment]
Hi,
Thanks for your fast answer!
My goal would be: having the first picture as a reference, I'd like to measure the strain of that object (which can increase of a few percents very quickly) over time.
I could definitely try to ramp the deformation to help the convergence, but even in that case, it's hard to make it converge, probably due to small variations of luminosity / vibrations, ...

Concerning deg_e and deg_n, are you talking about the "Mesher" class ? They are equal to 1 by default. I also tried to increase the number of iterations, but it's clearly not helping.

The object on the images is a DEA, see: [https://www.spiedigitallibrary.org/conference-proceedings-of-spie/10594/105940N/The-NERD-setup--assessing-the-life-time-of-electrodes/10.1117/12.2294408.full](https://www.spiedigitallibrary.org/conference-proceedings-of-spie/10594/105940N/The-NERD-setup--assessing-the-life-time-of-electrodes/10.1117/12.2294408.full)

**Comment by PolymerGuy** [comment]
To me, it sounds like this should be possible (provided that the texture is "stuck" to the surface of the object). If you wish, you can send me a couple of images and I can give it a try. Variations in illumination is always a problem, but there might be some tricks that can be applied.
