### ISSUE TITLE
Error when running 'nosetests' on windows 10

### ISSUE THREAD

**Issue by rubsal** [PolymerGuy/muDIC#21]
I get the following error message when running 'nosetests muDIC' on windows after cloning the repo.

![image](https://user-images.githubusercontent.com/60654018/74141951-2b617000-4bf8-11ea-889f-6d9cf98412d4.png)

**Comment by PolymerGuy** [comment]
Fixed by 24a20d4bc708892e8f9d4e2ea32dc6faf4eafe62
