### ISSUE TITLE
Installation fails on Fedora 32 due to old scipy version

### ISSUE THREAD

**Issue by jritta** [PolymerGuy/muDIC#33]
**Description**
Installation of muDIC fails on Fedora 32 do to compilation errors of scipy 1.2.1. Using GCC version 10 a `Rank mismatch` in Fortran code causes an error.

**System**
* Fedora 32
* Kernel version 5.10.20-100.fc32.x86_64
* gcc 10.2.1 20201125

**Error Message**
```
gfortran:f77: /tmp/pip-install-sc4s_4iu/scipy_1c0e5b6a7f804c2d829fb4f592fd2acd/scipy/_build_utils/src/wrap_dummy_g77_abi.f
    error: Command "/usr/bin/gfortran -Wall -g -ffixed-form -fno-second-underscore -fPIC -O3 -funroll-loops -Iscipy/sparse/linalg/eigen/arpack/ARPACK/SRC -I/home/jritter/.virtualenvs/inscomex/lib/python3.8/site-packages/numpy/core/include -Ibuild/src.linux-x86_64-3.8/numpy/distutils/include -c -c scipy/sparse/linalg/eigen/arpack/ARPACK/SRC/cnaup2.f -o build/temp.linux-x86_64-3.8/scipy/sparse/linalg/eigen/arpack/ARPACK/SRC/cnaup2.o" failed with exit status 1
```
This is likely thrown by following compilation erros:
```
Error: Rank mismatch between actual argument at (1) and actual argument at (2) (scalar and rank-1)
```

**Possible solution**
Make use of a newer scipy version (see [here](https://github.com/scipy/scipy/issues/11611)).

Is it possible to just update the scipy version in setup.py?

Best
Jonas

**Comment by jritta** [comment]
On a `Fedora 30` system, Kernel version `5.6.13-100.fc30.x86_64`, and gcc `9.3.1 20200408` the installation works without any issues.

**Comment by PolymerGuy** [comment]
Hi and thanks for the bug report! I will verify that we can move to the current version of Scipy. I assume that its error occurs when muDIC is installed using PIP?

**Comment by jritta** [comment]
@PolymerGuy  Thanks for your reply. Yes, the error occurs when I try to install it via PIP. A 'manual' installation by cloning the repository I did not try so far.

**Comment by PolymerGuy** [comment]
@jritta I have now checked that all tests pass for Scipy 1.6.2 which hopefully fixes the issue. I will try to upload a fix later today and update the muDIC package accordingly. Thanks for the bug report!

**Comment by jritta** [comment]
@PolymerGuy perfect, just let me know when you updated it. I will then try to install it on Fedora 32 with gcc 10 and in case of success close the issue.

**Comment by PolymerGuy** [comment]
@jritta The muDIC package has now been updated

**Comment by jritta** [comment]
The installation works now without any problems, perfect!
Thank you very much @PolymerGuy for your fast help.
